- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
    - !type:AgeRequirement
      requiredAge: 21 # cats
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Medical
    - Security
    - Brig
    - Maintenance
    - External
  #start-backmen: currency
  minBankBalance: 200
  maxBankBalance: 400
  wageDepartment: Security
  wage: 100
  #end-backmen: currency
  special:
    - !type:AddComponentSpecial
      components:
        - type: PsionicBonusChance
          flatBonus: 0.025
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
