- type: department
  id: CentCom
  name: department-CentCom
  description: department-CentCom-description
  color: "#13db0f"
  weight: -5
  roles:
    - BKCCSecGavna
    - BKCCSecOfficer
    - BKCCOperator
    - BKCCOfficial
    - BKCCCargo
    - BKCCAssistant
    - BKCCAdmiral
  editorHidden: true
  accountNumber: 1350  #backmen: currency

- type: department
  id: Silicons
  name: department-Silicons
  description: department-Silicons-description
  color: "#191e9e"
  weight: 10
  roles:
    - BKBPLATech
    - BKBPLAMED
  editorHidden: true
  accountNumber: 1351  #backmen: currency
