# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

- type: loadout
  id: ClothingOuterWinterSeniorOfficer
  equipment: ClothingOuterWinterSeniorOfficer   # cats

- type: startingGear
  id: ClothingOuterWinterSeniorOfficer
  equipment:
    outerClothing: ClothingOuterWinterSeniorOfficer  # cats

# Pocket #Backmen

- type: loadout
  id: WeaponRevolverMatebaNew
  equipment:
    pocket1: WeaponRevolverMatebaNew

# Pocket 2 #Backmen

- type: loadout
  id: SpeedLoaderMagnum
  equipment:
    pocket2: SpeedLoaderMagnum
