- type: entity
  id: BookPrinterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: book printer machine board
  components:
  - type: MachineBoard
    prototype: BookPrinter
    stackRequirements:
      Capacitor: 2
      Manipulator: 2
      MatterBin: 2