- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  #start-backmen: currency
  minBankBalance: 166
  maxBankBalance: 266
  wageDepartment: Civilian
  wage: 66
  #end-backmen: currency

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
    neck: ClothingNeckHolyMedal # cats
    suitstorage: HolySable # cats
    outerClothing: ClothingWitchHunter # cats
    head: ClothingWhitsHunter # cats
    eyes: ClothingEyesEyepatch # cats
  storage:
    back:
    - Bible
    - RubberStampChaplain
