- type: job
  id: BKCCOperator
  name: job-name-centcomoper
  description: job-description-centcomoper
  playTimeTracker: JobCentralCommandOperator
  setPreference: true
  startingGear: OperatorGavna
  icon: JobIconCCOperator
  supervisors: job-supervisors-hoh
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobCentralCommandAssistant
#      time: 7200
      time: 3000    #cats
    - !type:DepartmentTimeRequirement
      department: CentCom
#      time: 14400
      time: 5000    #cats
    - !type:AgeRequirement
      requiredAge: 21 # cats
    - !type:DepartmentTimeRequirement
      department: Silicons
#      time: 6000
      time: 2000   #cats
  access:
    - CCCargo
    - CCSecurity
    - CentralCommand
    - CCOfficer
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: SpecForce
          actionBssActionName: ActionCentcomFtlAction
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: Psionic
        - type: DispelPower
        - type: AntagImmune
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: CentCom
  wage: 75

- type: jobIcon
  parent: JobIcon
  id: JobIconCCOperator
  icon:
    sprite: /Textures/_SpaceCats/Interface/Misc/centcom_icons.rsi
    state: revvizor

- type: entity
  parent: CentcomPDABackmen
  id: CCOperatorPDA
  name: Centcom Operator PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Pda
      id: IDCardCentComGavnaOperator
      state: pda-centcom
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      state: pda-centcom

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComGavnaOperator
  name: ID карта оператора ЦК
  components:
    - type: PresetIdCard
      job: BKCCOperator
    - type: Access
      tags:
        - CCCargo
        - CCSecurity
        - CentralCommand
        - CCOfficer
      groups:
        - AllAccess
